baseURL = "https://k1ngst0n911.github.io/"
locale = "en-us"
title = "k1ngst0n911"
theme="hugo-theme-nightfall"

[params]
user = "k1ngst0n"
hostname = "gh0stc3ll"

    [params.author]
        name = "Kingston Damour"
        email = "kingston@punchmeintheface.com"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/k1ngst0n911"
icon = "fa-brands fa-github"  # Add link to your icon font to `layouts/partials/custom-head.html`
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "x.com"
url = "https://x.com/KingstonDamour"
