baseURL = "https://k1ngst0n911.github.io/"
locale = "en-us"
title = "k1ngst0n911"
theme="hugo-theme-nightfall"

[params]
user = "user_kingston"
hostname = "hostname"

    [params.author]
        name = "Name_Mr Kingston"
        avatar = "/avatar.png"
        avatarSize = "size-m"
        email = "kingston@gmail.com"
        avatarFirst = false
