baseURL = "https://k1ngst0n911.github.io/"
locale = "en-us"
title = "k1ngst0n911"
theme="hugo-theme-nightfall"

[params]
user = "k1ngst0n"
hostname = "gh0stc3ll"

    [params.author]
        name = "Kingston Damour"
        email = "kingston@punchmeintheface.com"

